spring.application.name=final_project

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-2.c3uuck8mwgwb.ap-northeast-2.rds.amazonaws.com:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=ictfinal

#JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret=1234567890123456789012345678901234567890

tosspayments.secret-key=test_sk_AQ92ymxN34vvbBx9xd0vrajRKXvd

spring.config.import=application-secret.properties
naver.client-id=d3CrSWAbrzwq0qbeV1J_
naver.redirect-uri=http://localhost:8080/social/login/naver/callback
naver.login.uri=http://localhost:5173/social/login/naver
react.uri=http://localhost:5173
kakao.client-id=c80829e0f30e640e7b46302ebf2b0a0e
kakao.redirect-uri=http://localhost:8080/social/login/kakao/callback
kakao.login.uri=http://localhost:5173/social/login/kakao

spring.data.redis.host=localhost
spring.data.redis.port=6379